LOAD DATA
INFILE 'sales_data.csv'
INTO TABLE HR.SALES
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
SALES_NUMBER INTEGER EXTERNAL,
SALES_DATE_TIME "to_timestamp(:SALES_DATE_TIME, 'RR-MM-DD HH24:MI:SSXFF')",
MEMBER_CODE INTEGER EXTERNAL,
REDEEMED_POINTS INTEGER EXTERNAL
)